version: "3"

services:
  db:
    build:
      context: .
      dockerfile: database/Dockerfile
    volumes:
      - ./database:/docker-entrypoint-initdb.d
    restart: on-failure
    environment:
      POSTGRES_USER: ${POSTGRES_USER?err}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD?err}
      POSTGRES_DB: ${POSTGRES_DB?err}
    ports:
      - 3000:5432
