version: "3"

services:
  db:
    image: postgres:14
    volumes:
      - ./database:/docker-entrypoint-initdb.d
    restart: on-failure
    environment:
      POSTGRES_USER: ${POSTGRES_USER?err}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD?err}
      POSTGRES_DB: ${POSTGRES_DB?err}
    ports:
      - 3000:5432

  server:
    build: ./server
    volumes:
      - ./server:/app
      - /app/node_modules
    restart: on-failure
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST?err}
      POSTGRES_PORT: ${POSTGRES_PORT?err}
      POSTGRES_USER: ${POSTGRES_USER?err}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD?err}
      POSTGRES_DB: ${POSTGRES_DB?err}
      SERVER_PORT: ${SERVER_PORT}
    ports:
      - 3001:3001
    depends_on:
      - db
